; ; PlatformIO Project Configuration File
; ;
; ;   Build options: build flags, source filter
; ;   Upload options: custom upload port, speed and extra flags
; ;   Library options: dependencies, extra library storages
; ;   Advanced options: extra scripting
; ;
; ; Please visit documentation for the other options and examples
; ; https://docs.platformio.org/page/projectconf.html

[env:nanoatmega168pa]
platform = atmelavr
framework = arduino
board = ATmega168P

board_build.f_cpu = 16000000L
board_upload.maximum_size = 16384

upload_protocol = custom
upload_command = avrdude -p m168p -c stk500v1 -P COM10 -b 19200 -U flash:w:$SOURCE:i

lib_deps = 
 	adafruit/Adafruit SSD1306@^2.5.17
 	adafruit/Adafruit GFX Library@^1.12.6
